# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 16:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0002_auto_20170127_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
    ]
