# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 18:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0005_auto_20170202_1752'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_app.Friend')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='register_app.User')),
            ],
        ),
    ]
