# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register_app', '0006_homie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homie',
            name='friend',
        ),
        migrations.RemoveField(
            model_name='homie',
            name='user',
        ),
        migrations.DeleteModel(
            name='Homie',
        ),
    ]
